In [2]:
import pandas as pd

In [7]:
print(pd.__version__)

3.0.1

In [8]:
pd.Series(["pranali","khushi","radhika","raghini"])

0    pranali
1     khushi
2    radhika
3    raghini
dtype: str

In [10]:
se=pd.Series(["Apple","Banana","Kiwi","Lichi","Mongo"],index=range(1,6))
se

1     Apple
2    Banana
3      Kiwi
4     Lichi
5     Mongo
dtype: str

In [15]:
se.values

<StringArray>
['Apple', 'Banana', 'Kiwi', 'Lichi', 'Mongo']
Length: 5, dtype: str

In [16]:
se.index

RangeIndex(start=1, stop=6, step=1)

In [17]:
dc={"name":"Priya","age":19,"branch":"computer","sur_name":"khan"}
d=pd.Series(dc)

In [18]:
d

name           Priya
age               19
branch      computer
sur_name        khan
dtype: object

In [19]:
d.size

4

In [20]:
d.dtype

dtype('O')

In [21]:
pd.DataFrame({"NAME":["PRNALI","RADHIKHA","SONIYA","PERNA","KHUSHI","PRAGTI"],
             "ID":[123,343,124,345,234,342],
             "TOTAL_MARKS":[454,345,390,454,490,333],
             "BRANCH":["COM","IT","EE","COM","COM","EE"],
             },index=range(1,7))

       NAME   ID  TOTAL_MARKS BRANCH
1    PRNALI  123          454    COM
2  RADHIKHA  343          345     IT
3    SONIYA  124          390     EE
4     PERNA  345          454    COM
5    KHUSHI  234          490    COM
6    PRAGTI  342          333     EE

In [22]:
pd.DataFrame([["lavnya","COM",23,2024],
             ["Rahul","IT",22,2025],
             ["Pragti","EE",20,2024],
             ["Komal","ML",21,2024],

              ["Pranali","COM",20,2025]],index=range(1,6),columns=["NAME","BRANCH","AGE","YEAR_OF ADDMISION"])

      NAME BRANCH  AGE  YEAR_OF ADDMISION
1   lavnya    COM   23               2024
2    Rahul     IT   22               2025
3   Pragti     EE   20               2024
4    Komal     ML   21               2024
5  Pranali    COM   20               2025

In [4]:
import pandas as pd
import numpy as np

In [53]:
data=pd.DataFrame({"EMPLOYEE_NAME":["SURESH","ADITY","YOGESH","KOMAL","PRACHI","YOGITA","HARNY","SAMRTH"],
                   "AGE":[23,25,54,46,45,65,34,54],
                   "LOACTION":["KALYAN","THANE","DOBIWALI","KURLA","DADER","NEW MUMBAI","THANE","VASHI"],
                   "SALARY":[23005,45466,65777,67556,68567,34545,43543,42333]},index=range(1,9))

In [54]:
data

  EMPLOYEE_NAME  AGE    LOACTION  SALARY
1        SURESH   23      KALYAN   23005
2         ADITY   25       THANE   45466
3        YOGESH   54    DOBIWALI   65777
4         KOMAL   46       KURLA   67556
5        PRACHI   45       DADER   68567
6        YOGITA   65  NEW MUMBAI   34545
7         HARNY   34       THANE   43543
8        SAMRTH   54       VASHI   42333

In [55]:
data.head()

  EMPLOYEE_NAME  AGE  LOACTION  SALARY
1        SURESH   23    KALYAN   23005
2         ADITY   25     THANE   45466
3        YOGESH   54  DOBIWALI   65777
4         KOMAL   46     KURLA   67556
5        PRACHI   45     DADER   68567

In [56]:
data.tail()

  EMPLOYEE_NAME  AGE    LOACTION  SALARY
4         KOMAL   46       KURLA   67556
5        PRACHI   45       DADER   68567
6        YOGITA   65  NEW MUMBAI   34545
7         HARNY   34       THANE   43543
8        SAMRTH   54       VASHI   42333

In [57]:
data.shape

(8, 4)

In [58]:
data.size

32

In [59]:
data.ndim

2

In [60]:
data.columns

Index(['EMPLOYEE_NAME', 'AGE', 'LOACTION', 'SALARY'], dtype='str')

In [61]:
data.values

array([['SURESH', 23, 'KALYAN', 23005],
       ['ADITY', 25, 'THANE', 45466],
       ['YOGESH', 54, 'DOBIWALI', 65777],
       ['KOMAL', 46, 'KURLA', 67556],
       ['PRACHI', 45, 'DADER', 68567],
       ['YOGITA', 65, 'NEW MUMBAI', 34545],
       ['HARNY', 34, 'THANE', 43543],
       ['SAMRTH', 54, 'VASHI', 42333]], dtype=object)

In [62]:
data.dtypes

EMPLOYEE_NAME      str
AGE              int64
LOACTION           str
SALARY           int64
dtype: object

In [63]:
data.info

<bound method DataFrame.info of   EMPLOYEE_NAME  AGE    LOACTION  SALARY
1        SURESH   23      KALYAN   23005
2         ADITY   25       THANE   45466
3        YOGESH   54    DOBIWALI   65777
4         KOMAL   46       KURLA   67556
5        PRACHI   45       DADER   68567
6        YOGITA   65  NEW MUMBAI   34545
7         HARNY   34       THANE   43543
8        SAMRTH   54       VASHI   42333>

In [64]:
data.describe()

             AGE       SALARY
count   8.000000      8.00000
mean   43.250000  48849.00000
std    14.849242  16817.85569
min    23.000000  23005.00000
25%    31.750000  40386.00000
50%    45.500000  44504.50000
75%    54.000000  66221.75000
max    65.000000  68567.00000

In [65]:
student=pd.DataFrame({"*STUDENT_NAME*":["pranali","raghini","prachi","yogita","mansi","vaishali","khushi","shubhagi","divya","riya"],
                      "AGE":[23,19,18,17,19,19,20,21,25,24],
                      "MARKS":[89,78,67,87,67,90,79,67,97,60],
                      "CITY":["kalyan","Thane","kurla","vashi","diva","kalva","dhigha","shahad","kalyan","ghatkhoper"]},index=range(1,11))

In [66]:
student

   *STUDENT_NAME*  AGE  MARKS        CITY
1         pranali   23     89      kalyan
2         raghini   19     78       Thane
3          prachi   18     67       kurla
4          yogita   17     87       vashi
5           mansi   19     67        diva
6        vaishali   19     90       kalva
7          khushi   20     79      dhigha
8        shubhagi   21     67      shahad
9           divya   25     97      kalyan
10           riya   24     60  ghatkhoper

In [69]:
employee=pd.DataFrame({"EMPLOYEES_ID":["E34","EETE3","ETR45","RET56","7E74","EE34Y","EE6UH5","RE7Q6","EWR87","EEY54"],
                       "EMPLOYEE_NAME":["RETESH","MANSI","ROHINI","PURVA","BAKTI","PALLWI","MONISHKA","KARTIK","KUSHAL","SHDHESH"],
                       "DEPARTMENT":["AI","TY","SSE","SE","CEO","HR","EMP","EMP","EL","EMP"],
                       "SALARY":[45000,45030,45466,67644,70545,67647,20566,23533,34756,37455]},index=range(1,11))

In [70]:
employee

   EMPLOYEES_ID EMPLOYEE_NAME DEPARTMENT  SALARY
1           E34        RETESH         AI   45000
2         EETE3         MANSI         TY   45030
3         ETR45        ROHINI        SSE   45466
4         RET56         PURVA         SE   67644
5          7E74         BAKTI        CEO   70545
6         EE34Y        PALLWI         HR   67647
7        EE6UH5      MONISHKA        EMP   20566
8         RE7Q6        KARTIK        EMP   23533
9         EWR87        KUSHAL         EL   34756
10        EEY54       SHDHESH        EMP   37455

In [9]:
product=pd.DataFrame([["2FE31","SHEMPOO",230,"300 GRAM"],
                     ["43FE","HAIR OLI",455,"500 LIT"],
                     ["54RTT","FACEPACK",100,"250 GRAM"],
                     ["786TY","LIPSTIC",149,"30 GRAM"],
                     ["45DF","PRFUME",249,"450 LIT"],
                     ["54SD","POWDER",100,"50 GRAM"]],index=range(1,7),columns=["PRODUCT_ID","PRODUCT_NAME","PRICE","QUANTITY"])

In [10]:
product

  PRODUCT_ID PRODUCT_NAME  PRICE  QUANTITY
1      2FE31      SHEMPOO    230  300 GRAM
2       43FE     HAIR OLI    455   500 LIT
3      54RTT     FACEPACK    100  250 GRAM
4      786TY      LIPSTIC    149   30 GRAM
5       45DF       PRFUME    249   450 LIT
6       54SD       POWDER    100   50 GRAM

In [14]:
d1=pd.DataFrame({"Student":["pranali","raghini","prachi","yogita","mansi","vaishali","khushi"],
              "Roll No":[345,564,34,454,677,565,878],
              "Branch":["CM","IT","CM","CO","EE","ML","IF"],
              "age":[23,19,23,24,20,19,20],
              "year_of_addmision":[2024,2025,2024,2026,2025,2023,2022],
              "5 subject marks":[np.random.randint(35,100,5)]},index=range(1,8))

In [13]:
import numpy as np

In [15]:
d1

    Student  Roll No Branch  age  year_of_addmision       5 subject marks
1   pranali      345     CM   23               2024  [71, 42, 87, 77, 99]
2   raghini      564     IT   19               2025  [71, 42, 87, 77, 99]
3    prachi       34     CM   23               2024  [71, 42, 87, 77, 99]
4    yogita      454     CO   24               2026  [71, 42, 87, 77, 99]
5     mansi      677     EE   20               2025  [71, 42, 87, 77, 99]
6  vaishali      565     ML   19               2023  [71, 42, 87, 77, 99]
7    khushi      878     IF   20               2022  [71, 42, 87, 77, 99]